Abundance_Nk.Web/Areas/Admin/ViewModels/TranscriptBursarViewModel.cs
using System.ComponentModel.DataAnnotations;
using Abundance_Nk.Model.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Abundance_Nk.Web.Areas.Admin.ViewModels
{
    public class TranscriptBursarViewModel
    {
         public TranscriptBursarViewModel()
        {
            transcriptRequest = new TranscriptRequest();
        }
        public List<TranscriptRequest> transcriptRequests { get; set; }
        public TranscriptRequest transcriptRequest { get; set; }
        public TranscriptStatus transcriptStatus { get; set; }
        public TranscriptClearanceStatus transcriptClearanceStatus { get; set; }
        public List<RemitaPayment> remitaPayments { get; set; }
        [DataType(DataType.Date)]
        public DateTime FromDateTime { get; set; }
        [DataType(DataType.Date)]
        public DateTime ToDateTime { get; set; }
    }
   
}

Abundance_Nk.Web/Areas/Admin/Controllers/TranscriptBursarController.cs
using Abundance_Nk.Business;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Areas.Admin.ViewModels;
using Abundance_Nk.Web.Controllers;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Abundance_Nk.Web.Areas.Admin.Controllers
{
    public class TranscriptBursarController : BaseController
    {
        TranscriptBursarViewModel viewModel;
        private MailMessage mail;
        public TranscriptBursarController()
        {
            mail = new MailMessage();
        }

        // GET: Admin/TranscriptBursar
        public ActionResult Index()
        {
            //rewrite this
            Person person;
            viewModel = new TranscriptBursarViewModel();
            TranscriptRequestLogic requestLogic = new TranscriptRequestLogic();
            PaymentEtranzactLogic paymentEtranzactLogic = new PaymentEtranzactLogic();
            RemitaPaymentLogic remitaPaymentLogic = new RemitaPaymentLogic();

            PersonLogic personLogic = new PersonLogic();
            
            try
            {
                viewModel.transcriptRequests = requestLogic.GetModelsBy(t => t.Date_Requested >= new DateTime(2016, 12, 1) && t.Date_Requested <= new DateTime(2017, 2, 8));

                List<TranscriptRequest> transcriptRequestList = new List<TranscriptRequest>();

                for (int i = 0; i < viewModel.transcriptRequests.Count; i++)
                {
                    TranscriptRequest transcriptRequest = viewModel.transcriptRequests[i];

                    person = personLogic.GetModelBy(p => p.Person_Id == transcriptRequest.student.Id);
                    transcriptRequest.student.FullName = person.FullName;
                    if (transcriptRequest.payment != null)
                    {
                        RemitaPayment remitaPayment = remitaPaymentLogic.GetModelBy(p => p.Payment_Id == transcriptRequest.payment.Id);
                        if (remitaPayment != null)
                        {
                            transcriptRequest.ConfirmationOrderNumber = remitaPayment.RRR;
                            transcriptRequest.remitaPayment = remitaPayment;
                            if (remitaPayment.Status.Contains("01:"))
                            {
                                transcriptRequest.Amount = remitaPayment.TransactionAmount.ToString();
                            }
                        }
                        else
                        {

                            transcriptRequest.Amount = "Payment not yet made";
                        }


                    }
                    transcriptRequestList.Add(transcriptRequest);
                }

                //foreach (TranscriptRequest transcriptRequest in viewModel.transcriptRequests)
                //{
                //    person = personLogic.GetModelBy(p => p.Person_Id == transcriptRequest.student.Id);
                //    transcriptRequest.student.FullName = person.FullName;
                //    if (transcriptRequest.payment != null)
                //    {
                //        RemitaPayment remitaPayment = remitaPaymentLogic.GetModelBy(p => p.Payment_Id == transcriptRequest.payment.Id);
                //        if (remitaPayment != null)
                //        {
                //            transcriptRequest.ConfirmationOrderNumber = remitaPayment.RRR;
                //            transcriptRequest.remitaPayment = remitaPayment;
                //            if (remitaPayment.Status.Contains("01:"))
                //            {
                //                transcriptRequest.Amount = remitaPayment.TransactionAmount.ToString();
                //            }
                //        }
                //        else
                //        {

                //            transcriptRequest.Amount = "Payment not yet made";
                //        }


                //    }
                //    transcriptRequestList.Add(transcriptRequest);
                //}


                viewModel.transcriptRequests = transcriptRequestList.OrderBy(t => t.RequestType).ThenBy(t => t.DestinationCountry).ThenBy(t => t.DateRequested).ToList();
                return View(viewModel);
            }
            catch (Exception)
            {

                return View(viewModel);
            }

        }

        [HttpGet]
        public ActionResult UpdateStatus(long tid, string confirmationOrder)
            {
                

                viewModel = new TranscriptBursarViewModel();
                try
                {
                    PaymentEtranzact paymentEtranzact = new PaymentEtranzact();
                    PaymentEtranzactLogic paymentEtranzactLogic = new PaymentEtranzactLogic();
                    paymentEtranzact = paymentEtranzactLogic.GetModelBy(p => p.Confirmation_No == confirmationOrder);
                    Person person;
                    PersonLogic personLogic = new PersonLogic();
                    TranscriptRequestLogic transcriptRequestLogic = new TranscriptRequestLogic();
                    TranscriptRequest tRequest = transcriptRequestLogic.GetModelBy(t => t.Transcript_Request_Id == tid);              
                    if (paymentEtranzact == null)
                    {
                        SetMessage("Payment cannot be confirmed at the moment" , Message.Category.Error);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        tRequest.transcriptStatus = new TranscriptStatus { TranscriptStatusId = 4 };
                        transcriptRequestLogic.Modify(tRequest);
                        person = personLogic.GetModelBy(p => p.Person_Id == tRequest.student.Id);
                        string studentMail = person.Email;
                        //MailSender("ugochukwuaronu@gmail.com", "lawsgacc@gmail.com");
                    }
                
                }
                catch (Exception ex)
                {
                    SetMessage("Error Occurred! " + ex.Message, Message.Category.Error);
                }
                SetMessage("Payment confirmed", Message.Category.Information);
                return RedirectToAction("Index");
            }
        public void MailSender(string StudentMail, string BursarMail)
        {
            try
            {
                 const string Subject = "Transcript Payment Confirmation";
                 const string Body = "This is to inform you that your transcript payment has been confirmed and your request processed";
                 if (ModelState.IsValid)
                {
                    mail.To.Add(StudentMail);
                    mail.From = new MailAddress(BursarMail);
                    mail.Subject = Subject;
                    mail.Body = Body;
                    mail.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 25;
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = new NetworkCredential("lawsgacc@gmail.com", "gaccount");
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                    TempData["msg"] = "Mail Sent";
                }
                else
                {
                    TempData["msg"] = "Mail Not Sent";
                }

            }
            catch (Exception e)
            {
                TempData["msg"] = "Mail Not Sent" + "\n" + e.Message;
            }
        }

        public ActionResult GetStatus(string order_Id)
        {
            try
            {
                RemitaSettings settings = new RemitaSettings();
                RemitaSettingsLogic settingsLogic = new RemitaSettingsLogic();
                settings = settingsLogic.GetModelBy(s => s.Payment_SettingId == 1);
                RemitaResponse remitaResponse = new RemitaResponse();
                RemitaPayment remitaPayment = new RemitaPayment();
                RemitaPaymentLogic remitaPaymentLogic = new RemitaPaymentLogic();
                remitaPayment = remitaPaymentLogic.GetModelBy(m => m.OrderId == order_Id);
                string remitaVerifyUrl = ConfigurationManager.AppSettings["RemitaVerifyUrl"].ToString();
                RemitaPayementProcessor remitaProcessor = new RemitaPayementProcessor(settings.Api_key);
                remitaResponse = remitaProcessor.TransactionStatus(remitaVerifyUrl, remitaPayment);
                if (remitaResponse != null && remitaResponse.Status != null)
                {
                    remitaPayment.Status = remitaResponse.Status + ":" + remitaResponse.StatusCode;
                    remitaPaymentLogic.Modify(remitaPayment);
                }
            }
            catch (Exception ex)
            {
                if (ex.Message.Contains("remote"))
                {
                    TempData["msg"] = "Could not get the status from the server, kindly try again. " + ex.Message;
                }
                else
                {
                    //throw ex;
                    TempData["msg"] = "Could not get the status from the server, kindly try again. " + ex.Message;
                }
            }

            return RedirectToAction("Index");
            
        }

        public ActionResult UpdateRRRBulk()
            {
                try
                {
                    BackgroundWorker m = new BackgroundWorker();
                    m.DoWork += m_DoWork;
                    var task1 = Task.Run(() => m.RunWorkerAsync());
                    RedirectToAction("Index");
                }
                catch (Exception)
                {
                
                    throw;
                }

Abundance_Nk.Web/Areas/Admin/Views/TranscriptBursar/CertificateReport.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.TranscriptBursarViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Transcript Report";
}
<div>
    @if(TempData["Message"] != null)
    {
        @Html.Partial("_Message",(Abundance_Nk.Model.Model.Message)TempData["Message"])
    }
</div>

<script type="text/javascript">
    $('.datepicker').datepicker(); //Initialise any date pickers
</script>

<h2>Incoming Certificate Payments</h2>
<h3>Total Payments made: @Model.remitaPayments.Count()</h3>
<div>

    <table class="table table-bordered table-hover table-striped table-responsive">

        <tr>
            <th>@Html.ActionLink("Full Name","Index",new { sortOrder = ViewBag.FullName,currentFilter = ViewBag.CurrentFilter })</th>
            <th>@Html.ActionLink("Date Requested","Index",new { sortOrder = ViewBag.FullName,currentFilter = ViewBag.CurrentFilter })</th>
            <th>@Html.ActionLink("Description","Index",new { sortOrder = ViewBag.Number,currentFilter = ViewBag.CurrentFilter })</th>
            <th>@Html.ActionLink("Amount","Index",new { sortOrder = ViewBag.Number,currentFilter = ViewBag.CurrentFilter })</th>

            <th>@Html.ActionLink("RRR","Index",new { sortOrder = ViewBag.Number,currentFilter = ViewBag.CurrentFilter })</th>
            @*<th>Reject</th>*@
        </tr>


        @for(int i = 0;i < Model.remitaPayments.Count;i++)
        {
            <tr>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].payment.Person.FullName)</td>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].TransactionDate)</td>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].Description)</td>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].TransactionAmount)</td>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].RRR)</td>
            </tr>
        }


    </table>



</div>

Abundance_Nk.Web/Areas/Admin/Views/TranscriptBursar/Index.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.TranscriptBursarViewModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@{
    ViewBag.Title = "Transcript Requests";
}
@section Scripts {
    @Scripts.Render("~/bundles/jquery")


    <link href="~/Scripts/DataTables-1.10.15/media/css/jquery.dataTables.css" rel="stylesheet" />
    <script src="~/Scripts/DataTables-1.10.15/media/js/jquery.dataTables.js"></script>
    <link href="~/Scripts/DataTables-1.10.15/extensions/Buttons/css/buttons.dataTables.css" rel="stylesheet" />
    <script src="~/Scripts/DataTables-1.10.15/extensions/Buttons/js/dataTables.buttons.js"></script>
    <script src="~/Scripts/DataTables-1.10.15/extensions/Buttons/js/buttons.colVis.js"></script>
    <script src="~/Scripts/DataTables-1.10.15/extensions/Responsive/js/dataTables.responsive.js"></script>


    <script src="~/Scripts/DataTables-1.10.15/buttons.flash.min.js"></script>
    <script src="~/Scripts/DataTables-1.10.15/buttons.html5.min.js"></script>
    <script src="~/Scripts/DataTables-1.10.15/buttons.print.min.js"></script>
    <script src="~/Scripts/DataTables-1.10.15/jszip.min.js"></script>
    <script src="~/Scripts/DataTables-1.10.15/pdfmake.min.js"></script>
    <script src="~/Scripts/DataTables-1.10.15/vfs_fonts.js"></script>


    <script type="text/javascript">

        $(document).ready(function () {

            $.extend($.fn.dataTable.defaults, {
                responsive: true
            });

            $('#studentTable').DataTable({
                dom: 'Bfrtip',
                ordering: true,
                buttons: [
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        }


                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        }

                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        }


                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        }


                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        }


                    }, , 'colvis'
                ]

                @*serverSide: true,
            ajax: '@Url.Action("StudentIdDataAjaxAsync", "UploadAdmission")'*@


            });


        });

    </script>
}

<div class="col-md-12">
    <div class="col-md-1"></div>
    <div class="col-md-12">

        <div>
            @if (TempData["Message"] != null)
            {
                @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
            }
        </div>

        <div class="panel panel-default">
            <div class="panel-heading panel-dark-head">
                <p><h2>Incoming Transcript Payment</h2></p>

                <a href="@Url.Action("UpdateRRRBulk")"><button class="btn btn-info">Update All</button></a>
            </div>
            <div class="panel-body">
                <div class="col-md-12">









                    <div class="col-md-12 table-responsive">



                        <table class="table table-bordered table-hover table-striped" id="studentTable">
                            <thead>
                                <tr>
                                    <th>@Html.ActionLink("Full Name", "Index", new { sortOrder = ViewBag.FullName, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>@Html.ActionLink("Matric Number", "Index", new { sortOrder = ViewBag.FullName, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>Request Type</th>
                                    <th>@Html.ActionLink("Date Requesterd", "Index", new { sortOrder = ViewBag.FullName, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>@Html.ActionLink("Destination", "Index", new { sortOrder = ViewBag.Number, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>@Html.ActionLink("RRR", "Index", new { sortOrder = ViewBag.Number, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>Confirm</th>
                                    <th>@Html.ActionLink("Amount Paid", "Index", new { sortOrder = ViewBag.Number, currentFilter = ViewBag.CurrentFilter })</th>

                                    @*<th>Reject</th>*@
                                </tr>
                            </thead>
                            <tbody style="color: black;">
                                @for (int i = 0; i < Model.transcriptRequests.Count; i++)
                                {
                                    var SN = i + 1;
                                    <tr>
                                        <td>@Html.DisplayTextFor(m => m.transcriptRequests[i].student.FullName)</td>
                                        <td>@Html.DisplayTextFor(m => m.transcriptRequests[i].student.MatricNumber)</td>
                                        @if (Model.transcriptRequests[i].RequestType == null)
                                        {
                                            <td>Transcript Request</td>
                                        }
                                        else
                                        {
                                            <td>@Html.DisplayTextFor(m => m.transcriptRequests[i].RequestType)</td>
                                        }

                                        <td>@Html.DisplayTextFor(m => m.transcriptRequests[i].DateRequested)</td>
                                        <td>@Html.DisplayTextFor(m => m.transcriptRequests[i].DestinationAddress)</td>
                                        <td>@Html.DisplayTextFor(m => m.transcriptRequests[i].ConfirmationOrderNumber)</td>
                                        <td>
                                            @if (Model.transcriptRequests[i].remitaPayment != null)
                                            {
                                                @*@Html.ActionLink("Confirm Payment", "UpdateStatus", "TranscriptBursar", new { tid = Model.transcriptRequests[i].Id, confirmationOrder = Model.transcriptRequests[i].ConfirmationOrderNumber }, new { @class = "btn btn-default", @id = "url" + i })*@
                                                @Html.ActionLink("Get Status", "GetStatus", "TranscriptBursar", new { order_Id = Model.transcriptRequests[i].remitaPayment.OrderId }, new { @class = "btn btn-default" })

                                            }
                                            else
                                            {
                                                @Html.Display("Invoice not yet generated")
                                            }
                                        </td>
                                        <td class="text-bold text-red">@Html.DisplayTextFor(m => m.transcriptRequests[i].Amount)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>



                </div>
            </div>
        </div>

    </div>
    <div class="col-md-1"></div>
</div>

Abundance_Nk.Web/Areas/Admin/Views/TranscriptBursar/TranscriptReport.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.TranscriptBursarViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Transcript Report";
}
<div>
    @if(TempData["Message"] != null)
    {
        @Html.Partial("_Message",(Abundance_Nk.Model.Model.Message)TempData["Message"])
    }
</div>

<script type="text/javascript">
    $('.datepicker').datepicker(); //Initialise any date pickers
</script>

<h2>Incoming Transcript Payments</h2>
<h3>Total Payments made: @Model.remitaPayments.Count()</h3>
<div>

    <table class="table table-bordered table-hover table-striped table-responsive">

        <tr>
            <th>@Html.ActionLink("Full Name","Index",new { sortOrder = ViewBag.FullName,currentFilter = ViewBag.CurrentFilter })</th>
            <th>@Html.ActionLink("Date Requesterd","Index",new { sortOrder = ViewBag.FullName,currentFilter = ViewBag.CurrentFilter })</th>
            <th>@Html.ActionLink("Description","Index",new { sortOrder = ViewBag.Number,currentFilter = ViewBag.CurrentFilter })</th>
            <th>@Html.ActionLink("Amount","Index",new { sortOrder = ViewBag.Number,currentFilter = ViewBag.CurrentFilter })</th>

            <th>@Html.ActionLink("RRR","Index",new { sortOrder = ViewBag.Number,currentFilter = ViewBag.CurrentFilter })</th>
            @*<th>Reject</th>*@
        </tr>


        @for(int i = 0;i < Model.remitaPayments.Count;i++)
        {
            <tr>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].payment.Person.FullName)</td>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].TransactionDate)</td>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].Description)</td>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].TransactionAmount)</td>
                <td>@Html.DisplayTextFor(m => m.remitaPayments[i].RRR)</td>
            </tr>
        }


    </table>



</div>

Abundance_Nk.Web/Areas/Admin/Views/TranscriptBursar/UpdateRRRBulk.cshtml
@{
    ViewBag.Title = "UpdateRRRBulk";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>UpdateRRRBulk</h2>
<p>Update is being run in the background.... Please check again after 30 minutes</p>