Abundance_Nk.Web/Areas/Admin/ViewModels/ChangeCourseViewModel.cs
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Windows.Forms;

namespace Abundance_Nk.Web.Areas.Admin.ViewModels
{

    public class ChangeCourseViewModel
    {
        public ChangeCourseViewModel()
        {
            ProgrammeSelectList = Utility.PopulateAllProgrammeSelectListItem();
            FeeTypeSelectList = Utility.PopulateFeeTypeSelectListItem();
            SessionSelectList = Utility.PopulateAllSessionSelectListItem();
        }
        public string ApplicationFormNumber { get; set; }
        public ApplicationForm ApplicationForm { get; set; }
        public AppliedCourse AppliedCourse { get; set; }
        public Person Person { get; set; }
        public Payment Payment { get; set; }
        public List<SelectListItem> ProgrammeSelectList { get; set; }
        public List<SelectListItem> DepartmentSelectListItem { get; set; }
        public List<SelectListItem> DepartmentOptionSelectListItem { get; set; }
        public decimal OldSchoolFees { get; set; }
        public decimal ShortFallAmount { get; set; }
        public AdmissionList AdmissionList { get; set; }
        public List<SelectListItem> FeeTypeSelectList { get; set; }
        public List<SelectListItem> SessionSelectList { get; set; }
        public FeeType FeeType { get; set; }
        public Session Session { get; set; }
        public string ShortFallFor { get; set; }
        public object Hash { get; internal set; }
        public RemitaPayment RemitaPayment { get; set; }
        public string ResponseUrl { get; internal set; }
    }
}

Abundance_Nk.Web/Areas/Admin/Controllers/ChangeCourseController.cs
using Abundance_Nk.Business;
using Abundance_Nk.Model.Entity.Model;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Areas.Admin.ViewModels;
using Abundance_Nk.Web.Areas.Student.ViewModels;
using Abundance_Nk.Web.Controllers;
using Abundance_Nk.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace Abundance_Nk.Web.Areas.Admin.Controllers
{
    [AllowAnonymous]
    public class ChangeCourseController : BaseController
    {
        ChangeCourseViewModel viewModel;
        // GET: Student/ChangeCourse
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SearchResult(ChangeCourseViewModel model)
        {
            viewModel = new ChangeCourseViewModel();
            try
            {
                ApplicationFormLogic applicationFormLogic = new ApplicationFormLogic();
                AppliedCourseLogic appliedCourseLogic = new AppliedCourseLogic();
                PersonLogic personLogic = new PersonLogic();
                ProgrammeLogic programmeLogic = new ProgrammeLogic();
                DepartmentLogic departmentLogic = new DepartmentLogic();
                ApplicationForm applicationForm = applicationFormLogic.GetModelBy(p => p.Application_Form_Number == model.ApplicationFormNumber);
                if (applicationForm != null)
                {
                    Person person = personLogic.GetModelBy(p => p.Person_Id == applicationForm.Person.Id);
                    List<Person> persons = personLogic.GetModelsBy(p => p.First_Name == person.FirstName && p.Last_Name == person.LastName && p.Date_Of_Birth == person.DateOfBirth && p.Date_Entered == person.DateEntered);
                    viewModel.Payment = isStudentAlreadyExist(persons);
                    AppliedCourse studentAppliedCourse = appliedCourseLogic.GetModelBy(p => p.Application_Form_Id == applicationForm.Id);
                    model.AppliedCourse = studentAppliedCourse;

                    getOldSchoolFees(model);

                    AppliedCourse appliedCourse = appliedCourseLogic.GetModelBy(p => p.Person_Id == person.Id);
                    viewModel.ApplicationForm = applicationForm;
                    viewModel.Person = person;
                    viewModel.AppliedCourse = appliedCourse;
                    ViewBag.ProgrammeId = viewModel.ProgrammeSelectList;
                    ViewBag.Departments = new SelectList(new List<Department>(), Utility.ID, Utility.NAME);

                    return View(viewModel);


                }
                else
                {
                    SetMessage("Invalid ApplicationFormNumber Form Number!", Message.Category.Error);
                }
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                SetMessage("Error Occured !" + ex.Message, Message.Category.Error);
                return RedirectToAction("Index");
            }
        }

        private void getOldSchoolFees(ChangeCourseViewModel model)
        {
            try
            {
                int levelId = GetLevel(model.AppliedCourse.Programme.Id);
                List<FeeDetail> oldSchoolFees = new List<FeeDetail>();
                FeeDetailLogic feeDetailLogic = new FeeDetailLogic();
                SessionLogic sessionLogic = new SessionLogic();
                Session session = sessionLogic.GetModelBy(p => p.Activated == true);
                oldSchoolFees = feeDetailLogic.GetModelsBy(p => p.Department_Id == model.AppliedCourse.Department.Id && p.Programme_Id == model.AppliedCourse.Programme.Id && p.Level_Id == levelId && p.Fee_Type_Id == (int)FeeTypes.SchoolFees && p.Session_Id == session.Id);
                decimal amount = oldSchoolFees.Sum(p => p.Fee.Amount);
                model.OldSchoolFees = amount;
                TempData["SchoolFees"] = amount;
            }
            catch (Exception)
            {

                throw;
            }
        }

        public ActionResult GetDepartmentAndLevelByProgrammeId(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    return null;
                }

                // List<Level> levels = null;
                List<Department> departments = null;
                Programme programme = new Programme() { Id = Convert.ToInt32(id) };
                if (programme.Id > 0)
                {
                    DepartmentLogic departmentLogic = new DepartmentLogic();
                    departments = departmentLogic.GetBy(programme);

                    //LevelLogic levelLogic = new LevelLogic();
                    //if (programme.Id <= 2)
                    //{
                    //    levels = levelLogic.GetONDs();
                    //}
                    //else if (programme.Id == 3 || programme.Id == 4)
                    //{
                    //    levels = levelLogic.GetHNDs();
                    //}
                    //else if (programme.Id == 5)
                    //{
                    //    levels = levelLogic.GetCertificateCourse();
                    //}
                }
                return Json(new { Departments = departments }, "json", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult GenerateInvoice(ChangeCourseViewModel model)
        {
            try
            {
                model.OldSchoolFees = (decimal)TempData["SchoolFees"];
                DepartmentLogic departmentLogic = new DepartmentLogic();
                PersonLogic personLogic = new PersonLogic();
                ApplicationFormLogic applicationFormLogic = new ApplicationFormLogic();
                ProgrammeLogic programmeLogic = new ProgrammeLogic();
                OLevelResultLogic olevelResultLogic = new OLevelResultLogic();
                OLevelResultDetailLogic olevelResultDetailLogic = new OLevelResultDetailLogic();
                //OLevelResult olevelResult = olevelResultLogic.GetModelsBy(p => p.Person_Id == model.Person.Id).LastOrDefault();
                //List<OLevelResultDetail> olevelResultDetail = olevelResultDetailLogic.GetModelsBy(p => p.Applicant_O_Level_Result_Id == olevelResult.Id);
                List<OLevelResult> olevelResult = olevelResultLogic.GetModelsBy(p => p.Person_Id == model.Person.Id);
                Department department = departmentLogic.GetModelBy(p => p.Department_Id == model.AppliedCourse.Department.Id);
                Programme programme = programmeLogic.GetModelBy(p => p.Programme_Id == model.AppliedCourse.Programme.Id);

                PaymentLogic paymentLogic = new PaymentLogic();
                List<Payment> oldPayments = paymentLogic.GetModelsBy(p => p.Person_Id == model.Person.Id);
                int feeTypeID = getFeeTypeId(oldPayments);

                if (model != null)
                {
                    using (TransactionScope scope = new TransactionScope())
                    {

                        model.AppliedCourse.Programme = programme;
                        model.AppliedCourse.Department = department;
                        CreatePerson(model);
                        model.Payment = CreatePayment(model, feeTypeID);
                        CreateAppliedCourse(model);
                        model.ApplicationForm = CreateApplicationForm(model);
                        foreach (OLevelResult item in olevelResult)
                        {
                            item.Person = model.Person;
                            item.ApplicationForm = model.ApplicationForm;
                            OLevelResult olevelResultNew = new OLevelResult();
                            olevelResultNew = olevelResultLogic.Create(item);
                            olevelResultNew.Person = model.Person;
                            olevelResultNew.ApplicationForm = model.ApplicationForm;
                            List<OLevelResultDetail> olevelResultDetail = olevelResultDetailLogic.GetModelsBy(p => p.Applicant_O_Level_Result_Id == item.Id);
                            CreateOLevelResultDetail(olevelResultNew, olevelResultDetail);

                        }
                        //olevelResult.Person = model.Person;
                        //olevelResult.ApplicationForm = model.ApplicationForm;
                        //olevelResult = olevelResultLogic.Create(olevelResult);
                        //olevelResult.Person = model.Person;
                        //olevelResult.ApplicationForm = model.ApplicationForm;
                        //CreateOLevelResultDetail(olevelResult, olevelResultDetail);
                        scope.Complete();
                    }

                    decimal FeeStatus = checkFeesPaid(oldPayments, model);

                    if (FeeStatus == 1)
                    {


                        List<FeeDetail> newPaymentFeeDetail = new List<FeeDetail>();

                        FeeDetailLogic feeDetailLogic = new FeeDetailLogic();
                        int LevelId = GetLevel(model.AppliedCourse.Programme.Id);
                        SessionLogic sessionLogic = new SessionLogic();
                        Session session = sessionLogic.GetModelBy(p => p.Activated == true);
                        newPaymentFeeDetail = feeDetailLogic.GetModelsBy(p => p.Department_Id == model.AppliedCourse.Department.Id && p.Programme_Id == model.AppliedCourse.Programme.Id && p.Level_Id == LevelId && p.Session_Id == session.Id);
                        TempData["FeeDetail"] = newPaymentFeeDetail;
                        return RedirectToAction("ShortFallInvoice", "Credential", new { Area = "Common", pmid = model.Payment.Id, });
                    }
                    else

Abundance_Nk.Web/Areas/Admin/Views/ChangeCourse/CardPayment.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.ChangeCourseViewModel
@{
    ViewBag.Title = "CardPayment";
    Layout = null;
}
<img src="~/Content/Images/payment_options.png" />
<form action="https://login.remita.net/remita/ecomm/finalize.reg" name="SubmitRemitaForm" method="POST">\
    <input name="merchantId" value="@Model.RemitaPayment.MerchantCode" type="hidden">
    <input name="hash" value="@Model.Hash" type="hidden">
    <input name="rrr" value="@Model.RemitaPayment.RRR" type="hidden">
    <input name="responseurl" value="@Model.ResponseUrl" type="hidden">
    <input type="submit" name="submit_btn" class="btn btn-danger mr5" value="Pay Via Remita using card">
</form>

Abundance_Nk.Web/Areas/Admin/Views/ChangeCourse/CreateShortFall.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.ChangeCourseViewModel
@{
    ViewBag.Title = "CreateShortFall";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("CreateShortFall", "ChangeCourse", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-1"></div>
                    <div class="col-md-10">
                        <div class="row">
                            <div>
                                @if (TempData["Message"] != null)
                                {
                                    @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
                                }
                                @if (TempData["Action"] != null)
                                {
                                    <div class="alert alert-dismissible alert-warning">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        <p>@TempData["Action"].ToString()</p>
                                    </div>
                                }
                            </div>
                        </div>

                        <div class="row">
                            <h3>Enter Application Form Number or Matric Number</h3>
                            <hr style="margin-top:0" />
                            <div class="col-md-12">

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">

                                            @Html.LabelFor(model => model.ApplicationFormNumber,"Application Form No / Matric No" ,new { @class = "control-label " })
                                            @Html.TextBoxFor(model => model.ApplicationFormNumber, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.ApplicationFormNumber, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <input class="btn btn-success btn-lg mr5" type="submit" name="submit" id="submit" value="Search" />
                                        </div>
                                    </div>


                                </div>
                            </div>

                        </div>

                        <br />





                    </div>

                </div>

                <div class="col-md-1"></div>
            </div>
        }




    </div>
    </div>

    @if (Model == null || Model.Person == null)
    {
        return;
    }
    @using (Html.BeginForm("CreateShortFallInvoice", "ChangeCourse", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ApplicationFormNumber)
        @Html.HiddenFor(model=>model.Person)

        <div class="panel panel-default ">
            <div class="panel-body ">
                <div class="col-md-12">
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Surname</label>
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.Person.LastName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Person.LastName)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">First Name</label>
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.Person.FirstName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Person.FirstName)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Other Names</label>
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.Person.OtherName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Person.OtherName)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Phone Number</label>
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.Person.MobilePhone, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Person.MobilePhone)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        @Html.DisplayFor(model => model.Person.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Person.Email)
                    </div>
                </div>
                @if (Model.AdmissionList != null)
                {
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Programme</label>
                        <div class="col-sm-10">
                            @Html.DisplayFor(model => model.AdmissionList.Programme.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.AdmissionList.Programme.Id)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Department</label>
                        <div class="col-sm-10">
                            @Html.DisplayFor(model => model.AdmissionList.Deprtment.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.AdmissionList.Deprtment.Id)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Application Form Number</label>
                        <div class="col-sm-10">
                            @Html.DisplayFor(model => model.ApplicationFormNumber, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ApplicationFormNumber)
                        </div>
                    </div>
                }
                <div class="form-group">
                    <label class="col-sm-2 control-label">Session</label>
                    <div class="col-sm-4">
                        @Html.DropDownListFor(model => model.Session.Id, (IEnumerable<SelectListItem>)ViewBag.Sessions, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.Session.Id)
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label">Shortfall For</label>
                    <div class="col-sm-4">
                        @Html.DropDownListFor(model => model.FeeType.Id, (IEnumerable<SelectListItem>)ViewBag.FeeTypes, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.FeeType.Id)
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label">Fee RRR</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(model => model.ShortFallFor, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.ShortFallFor)
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label">Enter ShortFall Amount</label>
                    <div class="col-sm-4">
                        @Html.TextBoxFor(model => model.ShortFallAmount, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.ShortFallAmount)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <input class="btn btn-success mr5" type="submit" name="submit" id="submit" value="Generate Invoice" />
                    </div>
                </div>
            </div>
        </div>

    }

Abundance_Nk.Web/Areas/Admin/Views/ChangeCourse/Index.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.ChangeCourseViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        @using(Html.BeginForm("SearchResult","ChangeCourse",FormMethod.Post))
        {
            @Html.AntiForgeryToken()
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <div class="row">
                    <div>
                        @if (TempData["Message"] != null)
                        {
                            @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
                        }
                        @if (TempData["Action"] != null)
                        {
                            <div class="alert alert-dismissible alert-warning">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                <p>@TempData["Action"].ToString()</p>
                            </div>
                        }
                    </div>
                </div>

                <div class="row">
                    <h3>Enter Application Form Number</h3>
                    <hr style="margin-top:0" />
                    <div class="col-md-12">

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">

                                    @Html.LabelFor(model => model.ApplicationFormNumber, new { @class = "control-label " })
                                    @Html.TextBoxFor(model => model.ApplicationFormNumber, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ApplicationFormNumber, null, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input class="btn btn-success btn-lg mr5" type="submit" name="submit" id="submit" value="Search" />
                                </div>
                            </div>

                           
                        </div>
                    </div>

                </div>

                <br />
         
                

              

            </div>

        </div>

        <div class="col-md-1"></div>
    </div>
        }


       


    </div>
</div>