Abundance_Nk.Web/Areas/Admin/ViewModels/UploadAdmissionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using Abundance_Nk.Business;
using Abundance_Nk.Model.Model;
using System.Web.Mvc;
using Abundance_Nk.Web.Models;
using System.ComponentModel.DataAnnotations;

namespace Abundance_Nk.Web.Areas.Admin.ViewModels
{
    public class UploadAdmissionViewModel
    {
        public AppliedCourseLogic appliedCourseLogic;
        public PersonLogic personLogic;
        private DepartmentLogic departmentLogic;
        public UploadAdmissionViewModel()
        {
            appliedCourseLogic = new AppliedCourseLogic();
            personLogic = new PersonLogic();
            departmentLogic = new DepartmentLogic();
            SessionSelectListItem = Utility.PopulateSessionSelectListItem();
            ProgrammeSelectListItem = Utility.PopulateAllProgrammeSelectListItem();
            AdmissionListTypeSelectListItem = Utility.PopulateAdmissionListTypeSelectListItem();
            if (Programme != null && Programme.Id > 0)
            {
                DepartmentSelectListItem = Utility.PopulateDepartmentSelectListItem(Programme);
                
            }
            LevelSelectListItem = Utility.PopulateLevelSelectListItem();
           
            
        }
        public Department Department { get; set; }
        public Programme Programme { get; set; }
        public Session CurrentSession { get; set; }
        public DepartmentOption DepartmentOption { get; set; }
        public Level Level { get; set; }
        [Display(Name="Admission List Type")]
        public AdmissionListType AdmissionListType { get; set; }
        public AdmissionListBatch AdmissionListBatch { get; set; }
        public List<SelectListItem> AdmissionListTypeSelectListItem { get; set; }
        public List<SelectListItem> DepartmentSelectListItem { get; set; }
        public List<SelectListItem> DepartmentOpionSelectListItem { get; set; }
        public List<SelectListItem> ProgrammeSelectListItem { get; set; }
        public List<SelectListItem> SessionSelectListItem { get; set; }
        public List<SelectListItem> LevelSelectListItem { get; set; }
        public AppliedCourse AppliedCourse { get; set; }
        public Person Person { get; set; }
        public HttpPostedFileBase File { get; set; }
        public List<AdmissionList> AdmissionList { get; set; }
        public AdmissionList AdmissionListDetail { get; set; }
        public List<AppliedCourse> AppliedCourseList { get; set; }
        public List<AdmissionList> AdmiissionLists { get; set; }
        public List<SelectListItem> DepartmentSelectList { get; set; }
        
        [Display(Name="Exam No / Application No")]
        public string SearchString { get; set; }
        public bool IsBulk { get; set; }

    }
    public class SampleAdmissionUpload
    {
        public string SN { get; set; }
        public string ApplicationNumber { get; set; }
    }
}

Abundance_Nk.Web/Areas/Admin/Controllers/UploadAdmissionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Abundance_Nk.Model.Entity;
using Abundance_Nk.Business;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Controllers;
using Abundance_Nk.Web.Areas.Admin.ViewModels;
using Abundance_Nk.Web.Models;
using System.Transactions;
using System.IO;
using System.Data.OleDb;
using Abundance_Nk.Model.Entity.Model;
using System.Web.UI.WebControls;

namespace Abundance_Nk.Web.Areas.Admin.Views
{
    public class UploadAdmissionController : BaseController
    {
        private const string ID = "Id";
        private const string NAME = "Name";
        private const string VALUE = "Value";
        private const string TEXT = "Text";
        private Abundance_NkEntities db = new Abundance_NkEntities();
        private UploadAdmissionViewModel viewmodel;
        //
        // GET: /Admin/UploadAdmission/
        public ActionResult UploadAdmission()
        {
            try
            {
                viewmodel = new UploadAdmissionViewModel();
                viewmodel.ProgrammeSelectListItem = Utility.PopulateAllProgrammeSelectListItem();
                viewmodel.SessionSelectListItem = Utility.PopulateAdmissionSessionSelectListItem();
                viewmodel.AdmissionListTypeSelectListItem = Utility.PopulateAdmissionListTypeSelectListItem();

                ViewBag.ProgrammeId = viewmodel.ProgrammeSelectListItem;
                ViewBag.SessionId = viewmodel.SessionSelectListItem;
                ViewBag.AdmissionListTypeId = viewmodel.AdmissionListTypeSelectListItem;
                ViewBag.DepartmentId = new SelectList(new List<Department>(), ID, NAME);
                ViewBag.DepartmentOptionId = new SelectList(new List<DepartmentOption>(), ID, NAME);

            }
            catch (Exception ex)
            {
                SetMessage("Error Occurred! " + ex.Message, Message.Category.Error);
            }

            return View();
        }

        public JsonResult GetDepartmentByProgrammeId(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    return null;
                }

                Programme programme = new Programme() { Id = Convert.ToInt32(id) };

                DepartmentLogic departmentLogic = new DepartmentLogic();
                List<Department> departments = departmentLogic.GetBy(programme);

                return Json(new SelectList(departments, ID, NAME), JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult UploadAdmission(UploadAdmissionViewModel vmodel)
        {
            try
            {
                DepartmentOptionLogic departmentOptionLogic = new DepartmentOptionLogic();

                if (vmodel.AdmissionListDetail.Form.ProgrammeFee.Programme != null && (vmodel.AdmissionListDetail.Form.ProgrammeFee.Programme.Id == (int)Programmes.HNDFullTime ||
                     vmodel.AdmissionListDetail.Form.ProgrammeFee.Programme.Id == (int)Programmes.HNDEvening || vmodel.AdmissionListDetail.Form.ProgrammeFee.Programme.Id == (int)Programmes.HNDPartTime))
                {
                    DepartmentOption departmentOption = departmentOptionLogic.GetModelsBy(d => d.Department_Id == vmodel.AdmissionListDetail.Deprtment.Id && d.Activated).LastOrDefault();
                    if (departmentOption != null && (vmodel.AdmissionListDetail.DepartmentOption == null || vmodel.AdmissionListDetail.DepartmentOption.Id <= 0))
                    {
                        SetMessage("Please select department option!", Message.Category.Error);
                        KeepApplicationFormInvoiceGenerationDropDownState(vmodel);
                        return View(vmodel);
                    }
                }
                
                KeepApplicationFormInvoiceGenerationDropDownState(vmodel);

                List<AppliedCourse> applicants = new List<AppliedCourse>();
                string pathForSaving = Server.MapPath("~/Content/ExcelUploads");
                string savedFileName = "";
                foreach (string file in Request.Files)
                {
                    HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
                    if (hpf.ContentLength == 0)
                        continue;
                    if (this.CreateFolderIfNeeded(pathForSaving))
                    {
                        FileInfo fileInfo = new FileInfo(hpf.FileName);
                        string fileExtension = fileInfo.Extension;
                        string newFile = "Admission" + "__";
                        string newFileName = newFile + DateTime.Now.ToString().Replace("/", "").Replace(":", "").Replace(" ", "") + fileExtension;

                        savedFileName = Path.Combine(pathForSaving,newFileName);
                        hpf.SaveAs(savedFileName);
                    }

                    IExcelManager excelManager = new ExcelManager();
                    DataSet dsAdmissionList = excelManager.ReadExcel(savedFileName);

                    if (dsAdmissionList != null && dsAdmissionList.Tables[0].Rows.Count > 0)
                    {
                        string Application_Number = "";

                        AppliedCourse appliedCourse = new AppliedCourse();
                        ApplicantJambDetail applicantJambDetail = new ApplicantJambDetail();
                        ApplicantJambDetailLogic applicantJambDetailLogic = new ApplicantJambDetailLogic();
                        AppliedCourseLogic appliedCourseLogic = new AppliedCourseLogic();

                        for (int i = 0; i < dsAdmissionList.Tables[0].Rows.Count; i++)
                        {
                            Application_Number = dsAdmissionList.Tables[0].Rows[i][1].ToString();

                            appliedCourse = appliedCourseLogic.GetModelsBy(m => m.APPLICATION_FORM.Application_Form_Number == Application_Number).LastOrDefault();
                            if (appliedCourse == null)
                            {
                                applicantJambDetail = applicantJambDetailLogic.GetModelsBy(a => a.Applicant_Jamb_Registration_Number == Application_Number && a.Application_Form_Id != null).LastOrDefault();
                                if (applicantJambDetail != null)
                                {
                                    if (applicantJambDetail.ApplicationForm != null)
                                    {
                                        appliedCourse = appliedCourseLogic.GetModelsBy(a => a.Application_Form_Id == applicantJambDetail.ApplicationForm.Id).LastOrDefault();   
                                    }
                                }
                            }

                            if (appliedCourse != null)
                            {
                                applicants.Add(appliedCourse);
                            }
                        }

                        vmodel.AppliedCourseList = applicants;
                        TempData["UploadAdmissionViewModel"] = vmodel;

                        return View(vmodel);
                    }
                }
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }

            KeepApplicationFormInvoiceGenerationDropDownState(vmodel);
            return View(vmodel);
        }

        [HttpPost]
        public ActionResult SaveAdmissionList(UploadAdmissionViewModel vmodel)
        {
            try
            {
                string operation = "INSERT";
                string action = "UPLOADING OF ADMISSION LIST";
                string client = Request.LogonUserIdentity.Name + " (" + HttpContext.Request.UserHostAddress + ")";

                vmodel = (UploadAdmissionViewModel)TempData["UploadAdmissionViewModel"];
                if (vmodel.AppliedCourseList != null && vmodel.AppliedCourseList.Count > 0)
                {
                    using (TransactionScope transaction = new TransactionScope())
                    {
                        AdmissionListBatch batch = new AdmissionListBatch();
                        AdmissionListBatchLogic batchLogic = new AdmissionListBatchLogic();
                        AdmissionListType AdmissionType = new AdmissionListType();
                        AdmissionListAudit AdmissionListAudit = new Model.Model.AdmissionListAudit();
                        UserLogic loggeduser = new UserLogic();
                        AdmissionType = vmodel.AdmissionListType;
                        batch.DateUploaded = DateTime.Now;
                        batch.IUploadedFilePath = "NAN";
                        batch.Type = AdmissionType;
                        batch = batchLogic.Create(batch);

                        AdmissionListAudit.Action = action;
                        AdmissionListAudit.Client = client;
                        AdmissionListAudit.Operation = operation;
                        AdmissionListAudit.Time = DateTime.Now;
                        AdmissionListAudit.User = loggeduser.GetModelBy(u => u.User_Name == User.Identity.Name);

                        for (int i = 0; i < vmodel.AppliedCourseList.Count; i++)
                        {
                            AdmissionList admissionlist = new AdmissionList();
                            AdmissionListLogic admissionListLogic = new AdmissionListLogic();
                            admissionlist.Form = vmodel.AppliedCourseList[i].ApplicationForm;
                            admissionlist.Deprtment = vmodel.AdmissionListDetail.Deprtment;
                            admissionlist.Programme = vmodel.AdmissionListDetail.Form.ProgrammeFee.Programme;

Abundance_Nk.Web/Areas/Admin/Views/UploadAdmission/EditAdmission.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.UploadAdmissionViewModel
@{   
    ViewBag.Title = "EditAdmission";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="~/Scripts/file-upload/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="~/Scripts/file-upload/jquery-ui-1.9.2.min.js"></script>
<script type="text/javascript" src="~/Scripts/file-upload/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="~/Scripts/jquery.print.js"></script>

<script type="text/javascript">
    
    $(document).ready(function() {

        $("#ProgrammeId").change(function() {

            $("#DepartmentId").empty();

            var programme = $("#ProgrammeId").val();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartmentByProgrammeId")', // we are calling json method
                dataType: 'json',
                data: { id: programme },
                success: function(departments) {
                    $("#DepartmentId").append('<option value="' + 0 + '"> -- Select -- </option>');

                    $.each(departments, function(i, department) {
                        $("#DepartmentId").append('<option value="' + department.Value + '">' + department.Text + '</option>');
                    });
                },
                error: function(ex) {
                    alert('Failed to retrieve departments.' + ex);
                }
            });
        });
    });

    function DeactivateAll() {
        if ($('#DeactivateAllId').is(':checked')) {
            $('.Deactivate').prop('checked', true);
        }
        else {
            $('.Deactivate').prop('checked', false);
        }
    }
    function ActivateAll() {
        if ($('#ActivateAllId').is(':checked')) {
            $('.Activate').prop('checked', true);
        }
        else {
            $('.Activate').prop('checked', false);
        }
    }

</script>


<div class="panel panel-default">
    <div class="panel-body">

        <div class="col-md-12">
            @if (TempData["Message"] != null)
            {
                @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
            }
            <div>
                <h4><p class="custom-text-black text-center ">Edit Admission List</p></h4>
            </div>
            @using (Html.BeginForm("EditAdmission", "UploadAdmission", FormMethod.Post))
            {

                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="panel panel-default ">
                    <div class="panel-body "> 

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.AdmissionListDetail.Form.ProgrammeFee.Programme.Id, "Programme", new { @class = "control-label custom-text-black" })
                                    @Html.DropDownListFor(model => model.Programme.Id, (IEnumerable<SelectListItem>)ViewBag.ProgrammeId, new { @class = "form-control", @required = "required", @id = "ProgrammeId" })
                                    @Html.ValidationMessageFor(model => model.Programme.Id, null, new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.AdmissionListDetail.Deprtment.Id, "Department ", new { @class = "control-label custom-text-black" })
                                    @Html.DropDownListFor(model => model.Department.Id, (IEnumerable<SelectListItem>)ViewBag.DepartmentId, new { @class = "form-control", @required = "required", @id = "DepartmentId" })
                                    @Html.ValidationMessageFor(model => model.AdmissionListDetail.Deprtment.Id, null, new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.CurrentSession.Id, new { @class = "control-label custom-text-black" })
                                    @Html.DropDownListFor(model => model.CurrentSession.Id, (IEnumerable<SelectListItem>)ViewBag.SessionId, new { @class = "form-control", @required = "required" })
                                    @Html.ValidationMessageFor(model => model.CurrentSession.Id, null, new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                </div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="col-sm-10">
                                <input class="btn btn-success mr5" type="submit" name="submit" id="submit" value="Edit" />

                            </div>
                        </div>
                    </div>
                </div>

            }

        </div>

        @if (Model == null || Model.AdmiissionLists == null) { return; }

        @if (Model != null && Model.AdmiissionLists != null)
        {
                using (Html.BeginForm("SaveEditedAdmission", "UploadAdmission", FormMethod.Post))
                {

                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.CurrentSession.Id)
                @Html.HiddenFor(model => model.Programme.Id)
                @Html.HiddenFor(model => model.Department.Id)

                <div class="col-md-12">

                    <table class="table table-bordered table-hover table-striped table-responsive">
                        <thead>
                            <tr>
                                <th>SN</th>
                                <th>Fullname</th>
                                <th>Application Number</th>
                                <th>Applied Department</th>
                                <th>Status</th>
                                <th>
                                    <input type="checkbox" id="DeactivateAllId" onclick="DeactivateAll()"/> Deactivate
                                </th>
                                <th>
                                    <input type="checkbox" id="ActivateAllId" onclick="ActivateAll()" /> Activate
                                </th>
                            </tr>
                        </thead>

                        <tbody style="color:black;">
                            @{ int N = 0;}
                            @for (var itemIndex = 0; itemIndex < Model.AdmiissionLists.Count; itemIndex++)
                            {
                                @Html.HiddenFor(model => model.AdmiissionLists[itemIndex].Id)

                                <tr>
                                    @{ N = itemIndex + 1; }
                                    <td>@N</td>
                                    <td>@Html.DisplayTextFor(m => m.AdmiissionLists[itemIndex].Form.Person.FullName)</td>
                                    <td>@Html.DisplayTextFor(m => m.AdmiissionLists[itemIndex].Form.Number)</td>@Html.HiddenFor(m => m.AdmiissionLists[itemIndex].Form.Number)
                                    <td>@Html.DisplayTextFor(m => m.AdmiissionLists[itemIndex].Deprtment.Name)</td>
                                    <td>@if (Model.AdmiissionLists[itemIndex].Activated.Value == true)
                                        {<p>Active</p>}
                                        else
                                        {<p>Not Active</p>}
                                    </td>
                                    <td>
                                        @Html.CheckBoxFor(m => m.AdmiissionLists[itemIndex].Deactivated, new {@type = "checkbox", @class = "Deactivate"})
                                    </td>
                                    <td>
                                        @Html.CheckBoxFor(m => m.AdmiissionLists[itemIndex].ActivateAlt, new { @type = "checkbox", @class = "Activate" })
                                    </td>
                                </tr>

                            }

                        </tbody>
                    </table>

                </div>

                <div class="form-group">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <input class="btn btn-success mr5" type="submit" name="submit" id="submit" value="Save" />

                    </div>
                </div>

                }
            
        }

    </div>
</div>

Abundance_Nk.Web/Areas/Admin/Views/UploadAdmission/EditAdmittedStudentDepartment.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.UploadAdmissionViewModel
@{
                /**/

                ViewBag.Title = "EditAdmittedStudentDepartment";
                Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="~/Scripts/file-upload/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="~/Scripts/file-upload/jquery-ui-1.9.2.min.js"></script>
<script type="text/javascript" src="~/Scripts/file-upload/jquery.fileupload-ui.js"></script>
<script type="text/javascript" src="~/Scripts/file-upload/jquery.fileupload.js"></script>
<script type="text/javascript" src="~/Scripts/file-upload/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="~/Scripts/jquery.print.js"></script>

<script type="text/javascript">
    var jqXHRData;
    $(document).ready(function () {

        $("#divDepartmentOption").hide();
        $("#AdmissionListDetail_Programme_Id").change(function () {

            $("#AdmissionListDetail_Deprtment_Id").empty();
            
            var programme = $("#AdmissionListDetail_Programme_Id").val();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartmentByProgrammeId")', // we are calling json method
                dataType: 'json',
                data: { id: programme },
                success: function (departments) {
                    $("#AdmissionListDetail_Deprtment_Id").append('<option value="' + 0 + '"> -- Select -- </option>');

                    $.each(departments, function (i, department) {
                        $("#AdmissionListDetail_Deprtment_Id").append('<option value="' + department.Value + '">' + department.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve departments.' + ex);
                }
            });
        });

        //Load Department Option
        $("#AdmissionListDetail_Deprtment_Id").change(function () {

            var department = $("#AdmissionListDetail_Deprtment_Id").val();
            var programme = $("#AdmissionListDetail_Programme_Id").val();

            $("#AdmissionListDetail_DepartmentOption_Id").empty();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartmentOptionByDepartment")', // we are calling json method
                dataType: 'json',
                data: { id: department, programmeid: programme },
                success: function (departmentOptions) {
                    //$("#hfDepartmentOptionExist").val(departmentOptions[0]);

                    if (!departmentOptions) {
                        $("#divDepartmentOption").hide();
                    }
                    else {
                        $("#AdmissionListDetail_DepartmentOption_Id").append('<option value="' + 0 + '"> -- Select -- </option>');
                        $.each(departmentOptions, function (i, Option) {
                            $("#AdmissionListDetail_DepartmentOption_Id").append('<option value="' + Option.Value + '">' + Option.Text + '</option>');
                        });
                        if (programme > 2 && programme != 6) {
                            $("#divDepartmentOption").show();
                        }
                    }
                },
                error: function (ex) {
                    alert('Failed to retrieve department Options.' + ex);
                }
            });

        })
        
})
</script>


@using (Html.BeginForm("EditAdmittedStudentDepartment", "UploadAdmission", new { area = "Admin" }, FormMethod.Post))
{
    @Html.HiddenFor(model => model.AdmissionListDetail.Id)
    @Html.HiddenFor(model => model.AdmissionListDetail.Form.Id)
    <div class="col-md-12">
        <div class="form-group" style="color:black">
            <h4>Edit Admission Details</h4>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AdmissionListDetail.Form.Person.FullName, new { @class = "col-sm-2 control-label " })
        <div class="col-sm-10">
            @Html.TextBoxFor(model => model.AdmissionListDetail.Form.Person.FullName, new { @class = "form-control", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.AdmissionListDetail.Form.Person.FullName, null, new { @class = "text-danger" })
        </div>

    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AdmissionListDetail.Form.Number, new { @class = "col-sm-2 control-label " })
        <div class="col-sm-10">
            @Html.TextBoxFor(model => model.AdmissionListDetail.Form.Number, new { @class = "form-control", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.AdmissionListDetail.Form.Number, null, new { @class = "text-danger" })
        </div>

    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AdmissionListDetail.Programme.Id, new { @class = "col-sm-2 control-label " })
        <div class="col-sm-10">
            @Html.DropDownListFor(model => model.AdmissionListDetail.Programme.Id, (IEnumerable<SelectListItem>)ViewBag.ProgrammeId, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AdmissionListDetail.Programme.Id, null, new { @class = "text-danger" })
        </div>

    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AdmissionListDetail.Deprtment.Id, new { @class = "col-sm-2 control-label " })
        <div class="col-sm-10">
            @Html.DropDownListFor(model => model.AdmissionListDetail.Deprtment.Id, (IEnumerable<SelectListItem>)ViewBag.DepartmentId, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AdmissionListDetail.Deprtment.Id, null, new { @class = "text-danger" })
        </div>

    </div>
    <div class="form-group" id="divDepartmentOption">
        @Html.LabelFor(model => model.AdmissionListDetail.DepartmentOption.Id, new { @class = "col-sm-2 control-label " })
        <div class="col-sm-10">
            @Html.DropDownListFor(model => model.AdmissionListDetail.DepartmentOption.Id, (IEnumerable<SelectListItem>)ViewBag.DepartmentOptionId, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AdmissionListDetail.DepartmentOption.Id, null, new { @class = "text-danger" })
        </div>

    </div>
    <div class="form-group">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
            <input class="btn btn-success mr5" type="submit" name="submit" id="submit" value="Update" />

        </div>
    </div>

}