Abundance_Nk.Web/Areas/Applicant/ViewModels/EWalletViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Models;

namespace Abundance_Nk.Web.Areas.Applicant.ViewModels
{
    public class EWalletViewModel
    {
        public EWalletViewModel()
        {
            ProgrammeSelectListItem = Utility.PopulateAllProgrammeSelectListItem();
            FeeTypeSelectListItem = Utility.PopulateActiveFeeTypeSelectListItem();
            SessionSelectListItem = Utility.PopulateSchoolFeesSessionSelectListItem();
            LevelSelectListItem = Utility.PopulateLevelSelectListItem();
            DepartmentSelectListItem = Utility.PopulateAllDepartmentSelectListItem();
            DepartmentOptionSelectListItem = Utility.PopulateDepartmentOptionSelectListItem();
        }
        public List<EWalletPayment> EWalletPayments { get; set; }

        public FeeType FeeType { get; set; }

        public PaymentType PaymentType { get; set; }
        public List<SelectListItem> ProgrammeSelectListItem { get; set; }
        public List<SelectListItem> DepartmentSelectListItem { get; set; }
        public List<SelectListItem> DepartmentOptionSelectListItem { get; set; }
        public List<SelectListItem> FeeTypeSelectListItem { get; set; }
        public List<SelectListItem> LevelSelectListItem { get; set; }
        public List<SelectListItem> SessionSelectListItem { get; set; }
        public EWalletPayment EWalletPayment { get; set; }
        public Model.Model.Student Student { get; set; }
        public StudentLevel StudentLevel { get; set; }
        public Person Person { get; set; }
        public Session Session { get; set; }
        public RemitaPayment RemitaPayment { get; set; }
        public string Hash { get; set; }

        public string ResponseUrl { get; set; }
        public ApplicationForm ApplicationForm { get; set; }
        public AdmissionList AdmissionList { get; internal set; }
    }
}

Abundance_Nk.Web/Areas/Student/ViewModels/EWalletViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Models;

namespace Abundance_Nk.Web.Areas.Student.ViewModels
{
    public class EWalletViewModel
    {
        public EWalletViewModel()
        {
            ProgrammeSelectListItem = Utility.PopulateAllProgrammeSelectListItem();
            FeeTypeSelectListItem = Utility.PopulateActiveFeeTypeSelectListItem();
            SessionSelectListItem = Utility.PopulateSchoolFeesSessionSelectListItem();
            LevelSelectListItem = Utility.PopulateLevelSelectListItem();
            DepartmentSelectListItem = Utility.PopulateAllDepartmentSelectListItem();
            DepartmentOptionSelectListItem = Utility.PopulateDepartmentOptionSelectListItem();
        }
        public List<EWalletPayment> EWalletPayments { get; set; }

        public FeeType FeeType { get; set; }

        public PaymentType PaymentType { get; set; }
        public List<SelectListItem> ProgrammeSelectListItem { get; set; }
        public List<SelectListItem> DepartmentSelectListItem { get; set; }
        public List<SelectListItem> DepartmentOptionSelectListItem { get; set; }
        public List<SelectListItem> FeeTypeSelectListItem { get; set; }
        public List<SelectListItem> LevelSelectListItem { get; set; }
        public List<SelectListItem> SessionSelectListItem { get; set; }
        public EWalletPayment EWalletPayment { get; set; }
        public Model.Model.Student Student { get; set; }
        public StudentLevel StudentLevel { get; set; }
        public Person Person { get; set; }
        public Session Session { get; set; }
        public RemitaPayment RemitaPayment { get; set; }
        public string Hash { get; set; }

        public string ResponseUrl { get; set; }
        public ApplicationForm ApplicationForm { get; set; }
        public AdmissionList AdmissionList { get; set; }
    }
}

Abundance_Nk.Web/Areas/Applicant/Controllers/EWalletController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Abundance_Nk.Business;
using Abundance_Nk.Model.Entity.Model;
using Abundance_Nk.Model.Model;
using Abundance_Nk.Web.Areas.Applicant.ViewModels;
using Abundance_Nk.Web.Controllers;
using Abundance_Nk.Web.Models;
using BarcodeLib;

namespace Abundance_Nk.Web.Areas.Applicant.Controllers
{
    [AllowAnonymous]
    public class EWalletController : BaseController
    {
        private Person _person;
        private PersonLogic _personLogic;
        private EWalletViewModel _viewModel;
        private EWalletPaymentLogic _eWalletPaymentLogic;
        public EWalletController()
        {
            _personLogic = new PersonLogic();
        }
        public ActionResult Index()
        {
            ApplicationFormLogic applicationFormLogic = new ApplicationFormLogic();
            _viewModel = new EWalletViewModel();
            var applicationFormNumber = TempData["AppNumber"] as string;
            TempData.Keep("AppNumber");
            var getApplicantDetails = applicationFormLogic.GetModelBy(a => a.Application_Form_Number == applicationFormNumber);

            _viewModel.ApplicationForm = getApplicantDetails;
            return View(_viewModel);
        }
        [HttpPost]
        public ActionResult Index(EWalletViewModel viewModel)
        {
            try
            {
                var applicationFormNumber = TempData["AppNumber"] as string;
                ApplicationFormLogic applicationFormLogic = new ApplicationFormLogic();
                ApplicationForm applicationForm = applicationFormLogic.GetModelsBy(a => a.Application_Form_Number == applicationFormNumber).LastOrDefault();
                if (applicationForm == null)
                {
                    SetMessage("Application form not found.", Message.Category.Error);
                    return View(viewModel);
                }

                viewModel.ApplicationForm = applicationForm;

                _eWalletPaymentLogic = new EWalletPaymentLogic();
                viewModel.EWalletPayments = _eWalletPaymentLogic.GetModelsBy(s => s.Person_Id == applicationForm.Person.Id);

                viewModel.EWalletPayments.ForEach(e =>
                {
                    e.PaymentStatus = _eWalletPaymentLogic.GetPaymentStatus(e);
                    e.RRR = _eWalletPaymentLogic.GetPaymentPin(e);
                });

                if (viewModel.EWalletPayments != null && viewModel.EWalletPayments.Count > 0)
                    viewModel.EWalletPayments = viewModel.EWalletPayments.OrderBy(e => e.Session.Id).ThenBy(e => e.FeeType.Id).ThenBy(e => e.Payment.DatePaid).ToList();
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }
        public ActionResult GenerateInvoice(string personId)
        {
            _viewModel = new EWalletViewModel();
            try
            {
                long applicantId = Convert.ToInt64(Utility.Decrypt(personId));

                _viewModel.FeeType = new FeeType() { Id = (int)FeeTypes.ShortFall };
                _viewModel.PaymentType = new PaymentType() { Id = 2 };

                AdmissionListLogic admissionListLogic = new AdmissionListLogic();
                AdmissionList admissionList = admissionListLogic.GetModelsBy(s => s.APPLICATION_FORM.Person_Id == applicantId).LastOrDefault();

                ViewBag.Sessions = _viewModel.SessionSelectListItem;
                ViewBag.Programmes = _viewModel.ProgrammeSelectListItem;
                ViewBag.Departments = _viewModel.DepartmentSelectListItem;
                ViewBag.Levels = _viewModel.LevelSelectListItem;
                TempData["ApplicantSession"] = admissionList.Session.Id;
                TempData.Keep("ApplicantSession");

                if (admissionList != null)
                {
                    PersonLogic personLogic = new PersonLogic();

                    _viewModel.Person = personLogic.GetModelBy(p => p.Person_Id == applicantId);
                    _viewModel.AdmissionList = admissionList;

                    ViewBag.Programmes = new SelectList(_viewModel.ProgrammeSelectListItem, Utility.VALUE, Utility.TEXT, _viewModel.AdmissionList.Programme.Id);
                    ViewBag.Departments = new SelectList(_viewModel.DepartmentSelectListItem, Utility.VALUE, Utility.TEXT, _viewModel.AdmissionList.Deprtment.Id);
                }
            }
            catch (Exception ex)
            {
                SetMessage("Error Occurred! " + ex.Message, Message.Category.Error);
            }

            return View(_viewModel);
        }
        [HttpPost]
        public ActionResult GenerateInvoice(EWalletViewModel viewModel)
        {
            try
            {
                RemitaPaymentLogic remitaPaymentLogic = new RemitaPaymentLogic();
                EWalletPaymentLogic walletPaymentLogic = new EWalletPaymentLogic();
                SessionLogic sessionLogic = new SessionLogic();
                PaymentLogic paymentLogic = new PaymentLogic();
                decimal Amt = 0M;
                Amt = viewModel.EWalletPayment.Amount;
                var applicantSession = TempData["ApplicantSession"];
                int convertedSession = Convert.ToInt16(applicantSession);
                Session session = sessionLogic.GetModelBy(s => s.Session_Id == convertedSession);

                if (Amt < 5000M)
                {
                    SetMessage("Amount must be greater than N5000!", Message.Category.Error);
                    return RedirectToAction("GenerateInvoice", new { personId = Utility.Encrypt(viewModel.Person.Id.ToString()) });
                }

                //check programme
                AdmissionListLogic admissionListLogic = new AdmissionListLogic();
                ApplicantLogic applicantLogic = new ApplicantLogic();
                AdmissionList admissionList = admissionListLogic.GetModelsBy(s => s.APPLICATION_FORM.Person_Id == viewModel.Person.Id).LastOrDefault();

                bool isFirstInvoice = IsFirstInvoice(session, viewModel.Person);

                //check if paid first invoice generated
                if (!isFirstInvoice)
                {
                    bool paidFirstInvoice = PaidFirstInvoice(session, viewModel.Person);
                    if (!paidFirstInvoice)
                    {
                        SetMessage("Kindly make payment for the first deposit invoice before making other deposits!", Message.Category.Error);
                        return RedirectToAction("GenerateInvoice", new { personId = Utility.Encrypt(viewModel.Person.Id.ToString()) });
                    }
                }
                


                int[] allowedProgrammes = { (int)Programmes.HNDEvening, (int)Programmes.HNDPartTime, (int)Programmes.NDEveningFullTime, (int)Programmes.NDPartTime };

                if (admissionList == null || !allowedProgrammes.Contains(admissionList.Programme.Id))
                {
                    SetMessage("You cannot use this means of payment.", Message.Category.Error);
                    return RedirectToAction("GenerateInvoice", new { personId = Utility.Encrypt(viewModel.Person.Id.ToString()) });
                }

                //check for normal installmental payment
                List<Payment> otherPaymentOptions = paymentLogic.GetModelsBy(p => p.Person_Id == viewModel.Person.Id && p.Fee_Type_Id == (int)FeeTypes.SchoolFees && p.Session_Id == session.Id);
                for (int i = 0; i < otherPaymentOptions.Count; i++)
                {
                    long currentPaymentId = otherPaymentOptions[i].Id;

                    EWalletPayment walletPayment = walletPaymentLogic.GetModelsBy(p => p.Payment_Id == currentPaymentId).LastOrDefault();
                    if (walletPayment == null)
                    {
                        SetMessage("You have already generated invoice for installmental payment, hence cannot use the E-Wallet!", Message.Category.Error);
                        return RedirectToAction("GenerateInvoice", new { personId = Utility.Encrypt(viewModel.Person.Id.ToString()) });
                    }
                }

                Payment payment = null;

                using (TransactionScope transaction = new TransactionScope())
                {
                    FeeType feeType = new FeeType() { Id = (int)FeeTypes.ShortFall };
                    viewModel.FeeType = feeType;
                    payment = CreatePayment(viewModel);

                    if(isFirstInvoice)
                    {
                        applicantLogic.UpdateStatus(admissionList.Form, ApplicantStatus.Status.GeneratedSchoolFeesInvoice);
                    }

                    //Get Payment Specific Setting
                    RemitaSettings settings = new RemitaSettings();
                    RemitaSettingsLogic settingsLogic = new RemitaSettingsLogic();
                    settings = settingsLogic.GetBy(1);

                    //Get Split Specific details;
                    List<RemitaSplitItems> splitItems = new List<RemitaSplitItems>();
                    RemitaSplitItems singleItem = new RemitaSplitItems();
                    RemitaSplitItemLogic splitItemLogic = new RemitaSplitItemLogic();

                    singleItem = splitItemLogic.GetBy(1);
                    singleItem.deductFeeFrom = "1";
                    splitItems.Add(singleItem);
                    singleItem = splitItemLogic.GetBy(2);
                    singleItem.deductFeeFrom = "0";
                    singleItem.beneficiaryAmount = Convert.ToString(Amt - Convert.ToDecimal(splitItems[0].beneficiaryAmount));
                    splitItems.Add(singleItem);

Abundance_Nk.Web/Areas/Applicant/Views/EWallet/CardPayment.cshtml
@model Abundance_Nk.Web.Areas.Applicant.ViewModels.EWalletViewModel
@{
    ViewBag.Title = "CardPayment";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = null;
}
<img src="~/Content/Images/payment_options.png" />
<form action="https://login.remita.net/remita/ecomm/finalize.reg" name="SubmitRemitaForm" method="POST">
@*<form action="http://www.remitademo.net/remita/ecomm/finalize.reg" name="SubmitRemitaForm" method="POST">*@
    <input name="merchantId" value="@Model.RemitaPayment.MerchantCode" type="hidden">
    <input name="hash" value="@Model.Hash" type="hidden">
    <input name="rrr" value="@Model.RemitaPayment.RRR" type="hidden">
    <input name="responseurl" value="@Model.ResponseUrl" type="hidden">
    <input type="submit" name="submit_btn" class="btn btn-danger mr5" value="Pay Via Remita using card">
</form>

Abundance_Nk.Web/Areas/Applicant/Views/EWallet/GenerateInvoice.cshtml
@model Abundance_Nk.Web.Areas.Applicant.ViewModels.EWalletViewModel

@{
    ViewBag.Title = "Wallet Deposit";
    Layout = "~/Views/Shared/_NewThemeLayout.cshtml";
}

<link rel="stylesheet" href="~/Content/sweetalert.css" />
<script type="text/javascript" src="~/Scripts/jquery-2.1.3.min.js"></script>
<script type="text/javascript" src="~/Scripts/sweetalert.min.js"></script>

@using (Html.BeginForm("GenerateInvoice", "EWallet", FormMethod.Post))
{
    @Html.HiddenFor(model => model.FeeType.Id)
    @Html.HiddenFor(model => model.PaymentType.Id)
    @Html.HiddenFor(model => model.Person.Type.Id)
    @Html.HiddenFor(model => model.Person.Id)

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h2>Wallet Deposit</h2>
                    <p><b>Provide the session, level, amount to deposit and then click the Deposit button to generate an invoice.</b></p>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-1"></div>
                    <div class="col-md-10">
                        <div class="row">
                            <div>
                                @if (TempData["Message"] != null)
                                {
                                    var msg = (Abundance_Nk.Model.Model.Message)TempData["Message"];
                                    //@Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
                                    <script>swal("Attention!", '@msg.Description', "error");</script>
                                }
                            </div>
                        </div>

                        <div class="row">
                            <hr style="margin-top:0" />
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">

                                            @Html.LabelFor(model => model.Session.Id, new { @class = "control-label " })
                                            @Html.DropDownListFor(model => model.AdmissionList.Session.Id, (IEnumerable<SelectListItem>)ViewBag.Sessions, new { @class = "form-control", disabled = true, required = "required" })
                                            @Html.ValidationMessageFor(model => model.AdmissionList.Session.Id, null, new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.HiddenFor(model => model.AdmissionList.Programme.Id)
                                            @Html.LabelFor(model => model.AdmissionList.Programme.Id, new { @class = "control-label " })
                                            @Html.DropDownListFor(model => model.AdmissionList.Programme.Id, (IEnumerable<SelectListItem>)ViewBag.Programmes, new { @class = "form-control", disabled = true })
                                            @Html.ValidationMessageFor(model => model.AdmissionList.Programme.Id, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.HiddenFor(model => model.AdmissionList.Deprtment.Id)
                                            @Html.LabelFor(model => model.AdmissionList.Deprtment.Id, "Course", new { @class = "control-label " })
                                            @Html.DropDownListFor(model => model.AdmissionList.Deprtment.Id, (IEnumerable<SelectListItem>)ViewBag.Departments, new { @class = "form-control", disabled = true })
                                            @Html.ValidationMessageFor(model => model.AdmissionList.Deprtment.Id, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.EWalletPayment.Amount, "Amount", new { @class = "control-label " })
                                            @Html.TextBoxFor(model => model.EWalletPayment.Amount, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.EWalletPayment.Amount, null, new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-md-1"></div>
            </div>

            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-10 ">
                        <div class="form-group">
                            <div class="col-md-12">
                                <input class="btn btn-success btn-lg mr5" type="submit" name="submit" id="submit" value="Deposit" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                </div>
            </div>


        </div>
    </div>
}

Abundance_Nk.Web/Areas/Applicant/Views/EWallet/Index.cshtml
@using Abundance_Nk.Model.Model
@using Abundance_Nk.Web.Models
@model Abundance_Nk.Web.Areas.Applicant.ViewModels.EWalletViewModel
@{
    ViewBag.Title = "E-Wallet";
    Layout = "~/Views/Shared/_NewThemeLayout.cshtml";
}

<link rel="stylesheet" href="~/Content/sweetalert.css" />
<script type="text/javascript" src="~/Scripts/jquery-2.1.3.min.js"></script>
<script type="text/javascript" src="~/Scripts/sweetalert.min.js"></script>

<script type="text/javascript">
        $(document).ready(function () {
            swal("Attention!", "NB: You cannot use installmental payment once you have started depositing to your e-wallet.");
        });

</script>

<div class="col-md-12">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-12">
                @if (TempData["Message"] != null)
                {
                    @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
                }
            </div>
        </div>
        @using (Html.BeginForm("Index", "EWallet", FormMethod.Post))
        {
            
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ApplicationForm.Number, "Application Number", new { @class = "control-label " })
                        @Html.TextBoxFor(model => model.ApplicationForm.Number, new { @class = "form-control", disabled="disabled", required = "required", value = Model.ApplicationForm.Number })
                        @Html.ValidationMessageFor(model => model.ApplicationForm.Number, null, new { @class = "text-danger" })
                    </div>


                </div>
            </div>
           


                <div class="row">
                    <div class="col-md-4 ">
                        <div class="form-group">
                            <div class="col-md-12">
                                <input class="btn btn-success btn-lg mr5" type="submit" name="submit" id="submit" value="Submit" />
                            </div>
                        </div>
                    </div>
                </div>
                }

                @if (Model != null && Model.ApplicationForm != null)
                {
                    <div class="row">
                        <div class="col-md-12">
                            @Html.ActionLink("Fund Wallet", "GenerateInvoice", new { controller = "EWallet", area = "Applicant", personId = Utility.Encrypt(Model.ApplicationForm.Person.Id.ToString()) }, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                    <br />
                    <br />
                }


                @if (Model != null && Model.EWalletPayments != null && Model.EWalletPayments.Count > 0)
                {
                    List<int> distinctSessionIds = Model.EWalletPayments.Select(e => e.Session.Id).Distinct().ToList();

                    for (int i = 0; i < distinctSessionIds.Count; i++)
                    {
                        int currentSessionId = distinctSessionIds[i];
                        List<EWalletPayment> payments = Model.EWalletPayments.Where(s => s.Session.Id == currentSessionId).ToList();

                        <div class="row">
                            <div class="col-md-12">
                                <b>@payments.FirstOrDefault().Session.Name Academic Year</b>
                                <div class="pull-left record-count-label">
                                    <label class="caption">Number of Payment Invoice:</label>&nbsp;
                                    <span class="badge" style="background-color: gray; border-radius: 2px !important; color: white !important;">@payments.Count</span>&nbsp;<br />

                                    <label class="caption">Successful Payments:</label>&nbsp;
                                    <span class="badge" style="background-color: gray; border-radius: 2px !important; color: white !important">@payments.Count(p => p.PaymentStatus)</span>&nbsp;<br />

                                    <span class="caption">Wallet Ballance:</span>&nbsp;
                                    <span class="badge" style="background-color: gray; border-radius: 2px !important; color: white !important; font-size: 20px !important;">@payments.Where(p => p.PaymentStatus).Sum(p => p.Amount).ToString("n")</span>
                                </div>
                            </div>
                        </div>
                        <br />
                        if (payments.Any(p => p.PaymentStatus))
                        {
                            <div class="row">
                                <div class="col-md-12">
                                    @Html.ActionLink("Overall Receipt", "SessionReceipt", "EWallet", new { Area = "Applicant", sessionId = @payments[0].Session.Id, personId = Utility.Encrypt(Model.EWalletPayments.FirstOrDefault().Person.Id.ToString()) }, new { @class = "btn btn-primary", target = "_blank" })
                                </div>
                            </div>
                        }
                        <div class="row">
                            <div class="col-md-12">
                                <h4>Deposit Records</h4>
                                <div class="table-responsive " style="font-size: 9pt">
                                    <table class="table table-condensed table-bordered grid-table table-head-alt mb30">
                                        <thead>
                                            <tr class="well" style="height: 35px; vertical-align: middle">

                                                <th>
                                                    Invoice Number
                                                </th>
                                                <th>
                                                    Payment Pin
                                                </th>
                                                <th>
                                                    Amount
                                                </th>
                                                <th>
                                                    Date Generated
                                                </th>
                                                <th>
                                                    Status
                                                </th>
                                                <th></th>
                                            </tr>
                                        </thead>

                                        @for (int j = 0; j < payments.Count; j++)
                                        {
                                            <tr>
                                                <td>
                                                    @payments[j].Payment.InvoiceNumber
                                                </td>

                                                <td>
                                                    @payments[j].RRR
                                                </td>

                                                <td class="unit">
                                                    @payments[j].Amount.ToString("n")
                                                </td>

                                                <td>
                                                    @payments[j].Payment.DatePaid.ToLongDateString()
                                                </td>
                                                @if (payments[j].PaymentStatus)
                                                {
                                                    <td>Paid</td>
                                                }
                                                else
                                                {
                                                    <td>Not Paid</td>
                                                }
                                                <td>
                                                    @Html.ActionLink("Reprint Invoice", "Invoice", "EWallet", new { Area = "Applicant", paymentId = Utility.Encrypt(payments[j].Payment.Id.ToString()) }, new { target = "_blank" }) &nbsp;
                                                    @if (payments[j].PaymentStatus)
                                                    {
                                                        @Html.ActionLink("Print Receipt", "Receipt", "EWallet", new { Area = "Applicant", paymentId = @payments[j].Payment.Id }, new { target = "_blank" })
                                                    }
                                                </td>
                                            </tr>
                                        }

                                    </table>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="row">
                        <div class="col-md-12">
                            <h5>No Deposit record found. Fund wallet using the "Fund Wallet" button.</h5> <br />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <span class="caption">Wallet Ballance: </span>&nbsp;
                            <span class="badge" style="background-color: gray; border-radius: 2px !important; color: white !important; font-size: 20px !important;">N0.00</span>
                        </div>
                    </div>
                }
            </div>
    <div class="col-md-1"></div>
</div>